name: chat_boilerplate
description: A minimal chat app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0-14.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true